name: Unit Test
run-name: Unit Test used test
on: [push]
jobs:
  steps:
       - uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install dependencies
        run: yarn

      - name: Run tests
        run: |
          yarn jest